from pydantic import BaseModel, Field
import base64
from fastapi import FastAPI, HTTPException
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519

import jwt
import datetime
import os

app = FastAPI(
    title="JWT Generator & Verifier Microservice",
    description="A robust API to securely generate and verify JSON Web Tokens (JWT) using EdDSA (Ed25519) cryptographic signatures.",
    version="1.0.0",
)

# Path to your private key file
PRIVATE_KEY_PATH = "getJwt"


def get_jwk():
    if not os.path.exists(PRIVATE_KEY_PATH):
        raise FileNotFoundError("Key file not found")

    with open(PRIVATE_KEY_PATH, "rb") as f:
        key_data = f.read()

    try:
        # load_ssh_private_key is much better at handling the keys
        # generated by 'ssh-keygen' on Windows/Linux.
        private_key = serialization.load_ssh_private_key(key_data, password=None)
        public_key = private_key.public_key()

        # Get the 32 raw bytes for Ed25519
        raw_pub_bytes = public_key.public_bytes(
            encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
        )

        # Base64URL encode and strip padding
        x_value = base64.urlsafe_b64encode(raw_pub_bytes).decode("utf-8").rstrip("=")

        return {
            "keys": [
                {
                    "alg": "EdDSA",
                    "crv": "Ed25519",
                    "x": x_value,
                    "kty": "OKP",
                    "kid": "get-jwt-manual-key-01",
                }
            ]
        }
    except Exception as e:
        # This will help you see if there's a different underlying error
        print(f"Error loading key: {e}")
        raise e


def get_private_key():
    if not os.path.exists(PRIVATE_KEY_PATH):
        raise FileNotFoundError(f"Private key not found at {PRIVATE_KEY_PATH}")
    with open(PRIVATE_KEY_PATH, "r") as f:
        return f.read()


@app.get("/")
def read_root():
    return {"status": "FastAPI JWT Generator is running"}


@app.get("/api/auth/jwks")
async def jwks_endpoint():
    try:
        return get_jwk()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


class TokenRequest(BaseModel):
    # Field(...) allows you to add descriptions and examples for Swagger
    payload: dict = Field(
        ...,
        examples=[{"user_id": "12345", "role": "admin", "email": "maruf@example.com"}],
        description="The custom data you want to include in the JWT",
    )
    expires_in_hours: int = Field(
        default=2, examples=[2], description="How many hours until the token expires"
    )


@app.post("/generate-token")
async def generate_token(request: TokenRequest):
    try:
        # 1. Read the file as raw bytes
        with open(PRIVATE_KEY_PATH, "rb") as f:
            key_data = f.read()

        # 2. Convert the OpenSSH format into a proper Key Object
        # This is the step that fixes "Not a public or private key"
        private_key_obj = serialization.load_ssh_private_key(key_data, password=None)

        # 3. Prepare payload
        data_to_encode = request.payload.copy()
        now = datetime.datetime.now(datetime.timezone.utc)
        data_to_encode.update(
            {
                "exp": now + datetime.timedelta(hours=request.expires_in_hours),
                "iat": now,
                "iss": "fastapi-jwt-provider",
            }
        )

        # 4. Sign using the Key Object (not the string)
        token = jwt.encode(
            data_to_encode,
            private_key_obj,  # Pass the object here
            algorithm="EdDSA",
            headers={"kid": "get-jwt-manual-key-01"},
        )

        return {"success": True, "token": token}

    except Exception as e:
        # Printing to console helps you debug the exact line
        print(f"Detailed Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


class VerifyRequest(BaseModel):
    token: str
    x: str  # The public key string from your /jwks


@app.post("/verify-token")
async def verify_token(request: VerifyRequest):
    try:
        # 1. Convert the 'x' string back to raw bytes
        # We add padding ('===') because Base64URL often strips it
        padding = "=" * (4 - len(request.x) % 4)
        public_key_bytes = base64.urlsafe_b64decode(request.x + padding)

        # 2. Load it as an Ed25519 Public Key object
        public_key_obj = ed25519.Ed25519PublicKey.from_public_bytes(public_key_bytes)

        # 3. Decode and Verify
        # This checks the signature, expiration (exp), and issuer (iss)
        decoded_payload = jwt.decode(
            request.token,
            public_key_obj,
            algorithms=["EdDSA"],
            issuer="fastapi-jwt-provider",
        )

        return {
            "valid": True,
            "message": "Signature and payload verified!",
            "payload": decoded_payload,
        }

    except jwt.ExpiredSignatureError:
        return {"valid": False, "message": "Token has expired"}
    except jwt.InvalidTokenError as e:
        return {"valid": False, "message": f"Invalid token: {str(e)}"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Verification failed: {str(e)}")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
